In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sb

In [2]:
df = pd.read_csv("/Users/PUSHPAK/OneDrive/Desktop/Spain_Project/data/normalized_2_songs.csv")

In [3]:
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,duration_min,song_id
0,2025-06-02,40,0 confianza,rvfv,35,217500,album,20,False,3.625,0 confianza_rvfv
1,2025-06-05,31,0 confianza,rvfv,57,217500,album,20,False,3.625,0 confianza_rvfv
2,2025-06-06,25,0 confianza,rvfv,57,217500,album,20,False,3.625,0 confianza_rvfv
3,2025-06-07,23,0 confianza,rvfv,57,217500,album,20,False,3.625,0 confianza_rvfv
4,2025-06-08,23,0 confianza,rvfv,57,217500,album,20,False,3.625,0 confianza_rvfv

In [4]:
df.isnull().sum()

date            0
position        0
song            0
artist          0
popularity      0
duration_ms     0
album_type      0
total_tracks    0
is_explicit     0
duration_min    0
song_id         0
dtype: int64

In [5]:
df['song_id'].nunique()

575

In [6]:
df.groupby('date').size().value_counts()

50    554
Name: count, dtype: int64

In [7]:
lifecycle = df.groupby('song_id').agg(
    entry_date=('date','min'),
    exit_date=('date','max'),
    peak_position=('position','min'),
    days_on_playlist=('date','count')
).reset_index()

In [9]:
lifecycle

,song_id,entry_date,exit_date,peak_position,days_on_playlist
0,0 confianza_rvfv,2025-06-02,2025-06-23,23,20
1,"1 de enero, puntacana_rels b",2025-04-28,2025-04-28,45,1
2,1000cosas_lola indigo & manuel turizo,2025-03-10,2025-11-13,3,245
3,100xciento_foreign teck & eladio carrion & de ...,2025-04-30,2025-05-15,13,11
4,14 febreros_quevedo,2025-11-24,2025-11-27,9,4
...,...,...,...,...,...
570,yo sé_yan block & torrres,2025-11-01,2025-11-27,8,26
571,yo tengo un novio_lola indigo,2024-12-17,2024-12-24,18,8
572,yotuloko_omar montes & rels b,2025-07-14,2025-11-05,22,114
573,"young miko: bzrp music sessions, vol. 58_bizar...",2025-01-13,2025-04-26,1,100
574,zorra_nebulossa,2025-02-05,2025-05-18,8,21

In [10]:
lifecycle['entry_date'] = pd.to_datetime(lifecycle['entry_date'])
lifecycle['exit_date'] = pd.to_datetime(lifecycle['exit_date'])

In [11]:
lifecycle['lifetime_days'] = (
    lifecycle['exit_date'] - lifecycle['entry_date']
).dt.days + 1

In [12]:
lifecycle.dtypes

song_id                     object
entry_date          datetime64[ns]
exit_date           datetime64[ns]
peak_position                int64
days_on_playlist             int64
lifetime_days                int64
dtype: object